---

- name: Find latest release version number
  block:
    - name: Find tag for latest release
      uri:
        url: "{{ graalvm_ce_latest_release_url }}"
        return_content: true
      register: json_response

    - name: get graalvm version from json response
      set_fact:
        graalvm_ce_version: "{{ json_response.json.tag_name[3:] }}"
  when: graalvm_ce_version == "latest"

  # Currently only setup for CentOS, can easily extend to other OS'
- name: Download and extract for CentOS
  block:
    - name: Build url
      set_fact:
        graalvm_ce_download_url: "https://github.com/\
          graalvm/graalvm-ce-builds/releases/download/\
          vm-{{ graalvm_ce_version }}/\
          graalvm-ce-java{{ graalvm_ce_java_version }}-linux-amd64-{{ graalvm_ce_version }}.tar.gz"

    - name: Set parent install folder
      set_fact:
        graalvm_ce_install_folder: "{{ graalvm_ce_install_location }}/graalvm-ce-java{{ graalvm_ce_java_version }}-{{ graalvm_ce_version }}"

    - name: Check if graalvm ce {{ graalvm_ce_version }} is already installed
      stat:
        path: "{{ graalvm_ce_install_folder }}"
      register: isInstalled

    - name: Download graalvm-ce
      get_url:
        url: "{{ graalvm_ce_download_url }}"
        dest: "~/.ansible/tmp/graalvm-ce-java{{ graalvm_ce_java_version }}-linux-amd64-{{ graalvm_ce_version }}.tar.gz"
      when: not isInstalled.stat.exists

    - name: Unarchive graalvm
      unarchive:
        src: "~/.ansible/tmp/graalvm-ce-java{{ graalvm_ce_java_version }}-linux-amd64-{{ graalvm_ce_version }}.tar.gz"
        dest: "{{ graalvm_ce_install_location }}"
        creates: "{{ graalvm_ce_install_folder }}"
        remote_src: true
        exclude:
          - "graalvm-ce-{{ graalvm_ce_version }}/src.zip"
      when: not isInstalled.stat.exists

    - name: Clean up
      file:
        state: absent
        path: "~/.ansible/tmp/graalvm-ce-java{{ graalvm_ce_java_version }}-linux-amd64-{{ graalvm_ce_version }}.tar.gz"

    - name: Create a symbolic link
      file:
        src: "{{ graalvm_ce_install_folder }}"
        dest: "{{ graalvm_ce_install_location }}/graalvm-ce"
        state: link

    - name: 'install Java environment variables'
      template:
        src: 'java.sh.j2'
        dest: '/etc/profile.d/java.sh'
        owner: root
        group: root

  when: ansible_distribution == "CentOS"
